package com.silverguardian.prototype;
import android.content.*;import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AlertDialog;import androidx.recyclerview.widget.*;import com.silverguardian.prototype.models.User;import com.silverguardian.prototype.utils.FormFieldFactory;import java.util.*;
public class LoginActivity extends BaseActivity{
 private EditText pinInput;private Button loginButton;private TextView selectedUserName;private UserAdapter adapter;private User selectedUser;private final List<User>users=new ArrayList<>();private boolean pinVisible;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_login);users.addAll(userSession().getUsers());pinInput=findViewById(R.id.pin_input);loginButton=findViewById(R.id.login_button);selectedUserName=findViewById(R.id.selected_user_name);RecyclerView g=findViewById(R.id.user_grid);g.setLayoutManager(new GridLayoutManager(this,3));adapter=new UserAdapter();g.setAdapter(adapter);findViewById(R.id.add_user_button).setOnClickListener(v->showAddUserDialog());findViewById(R.id.pin_visibility).setOnClickListener(v->togglePin());findViewById(R.id.forgot_pin).setOnClickListener(v->forgotPin());pinInput.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable e){loginButton.setEnabled(e.length()==4&&selectedUser!=null);}});loginButton.setOnClickListener(v->login());if(!users.isEmpty())selectUser(users.get(0));}
 private void togglePin(){pinVisible=!pinVisible;pinInput.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|(pinVisible?0:android.text.InputType.TYPE_NUMBER_VARIATION_PASSWORD));((ImageButton)findViewById(R.id.pin_visibility)).setImageResource(pinVisible?R.drawable.ic_visibility_off:R.drawable.ic_visibility);pinInput.setSelection(pinInput.length());}
 private void login(){if(selectedUser==null)return;String pin=pinInput.getText().toString().trim();if(pin.equals(selectedUser.pin)){userSession().setActiveUser(selectedUser.id);startActivity(new Intent(this,MainActivity.class).putExtra("user_id",selectedUser.id));finish();}else{Toast.makeText(this,R.string.login_invalid_pin_toast,Toast.LENGTH_SHORT).show();pinInput.setText("");}}
 private void forgotPin(){if(selectedUser==null)return;if(selectedUser.hintQuestion.isEmpty()||selectedUser.hintAnswer.isEmpty()){Toast.makeText(this,"该老人未设置 PIN 提示",Toast.LENGTH_LONG).show();return;}EditText answer=new EditText(this);answer.setHint("请输入提示答案");new AlertDialog.Builder(this).setTitle(selectedUser.hintQuestion).setView(answer).setPositiveButton("验证",null).setNegativeButton(R.string.common_cancel,null).create().setOnShowListener(x->{});AlertDialog d=new AlertDialog.Builder(this).setTitle(selectedUser.hintQuestion).setView(answer).setPositiveButton("验证",null).setNegativeButton(R.string.common_cancel,null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(answer.getText().toString().trim().equals(selectedUser.hintAnswer.trim())){new AlertDialog.Builder(this).setTitle("PIN 码").setMessage(selectedUser.pin).setPositiveButton(R.string.common_close,null).show();d.dismiss();}else answer.setError("答案不正确");}));d.show();}
 private void showAddUserDialog(){LinearLayout f=(LinearLayout)getLayoutInflater().inflate(R.layout.view_dialog_form_container,null,false);EditText n=FormFieldFactory.addTextField(this,f,"老人姓名","例如：颜爷爷",false),p=FormFieldFactory.addTextField(this,f,"4 位 PIN","请输入 4 位数字",false),a=FormFieldFactory.addTextField(this,f,"年龄","例如：70",false),c=FormFieldFactory.addTextField(this,f,"健康状况","可选",false),q=FormFieldFactory.addTextField(this,f,"提示问题","例如：我的生日是几号？",false),ans=FormFieldFactory.addTextField(this,f,"提示答案","可选",false);p.setInputType(2|16);a.setInputType(2);AlertDialog d=new AlertDialog.Builder(this).setTitle(R.string.login_add_user_title).setView(f).setPositiveButton(R.string.common_save,null).setNegativeButton(R.string.common_cancel,null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String name=n.getText().toString().trim(),pin=p.getText().toString().trim();if(name.isEmpty()){n.setError("请输入老人姓名");return;}if(!pin.matches("\\d{4}")){p.setError("请输入 4 位数字");return;}if(q.getText().length()>0&&ans.getText().toString().trim().isEmpty()){ans.setError("填写问题后也要填写答案");return;}int age=a.getText().length()==0?60:Integer.parseInt(a.getText().toString());User u=userSession().addUser(name,pin,age,c.getText().toString().trim(),q.getText().toString().trim(),ans.getText().toString().trim());users.clear();users.addAll(userSession().getUsers());selectUser(u);adapter.notifyDataSetChanged();d.dismiss();}));d.show();}
 private void selectUser(User u){selectedUser=u;selectedUserName.setText(u.name);adapter.notifyDataSetChanged();loginButton.setEnabled(pinInput.length()==4);}
 private class UserAdapter extends RecyclerView.Adapter<VH>{public VH onCreateViewHolder(android.view.ViewGroup p,int t){return new VH(getLayoutInflater().inflate(R.layout.item_user_avatar,p,false));}public void onBindViewHolder(VH h,int pos){User u=users.get(pos);h.name.setText(u.name);h.avatar.setText(u.name.substring(0,1));h.itemView.setSelected(u==selectedUser);h.itemView.setOnClickListener(v->selectUser(u));}public int getItemCount(){return users.size();}}
 private static class VH extends RecyclerView.ViewHolder{TextView name,avatar;VH(View v){super(v);name=v.findViewById(R.id.user_name);avatar=v.findViewById(R.id.user_avatar_text);}}
}