package com.silverguardian.prototype;
import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AlertDialog;import androidx.recyclerview.widget.*;import com.silverguardian.prototype.models.MedicineLibraryItem;import com.silverguardian.prototype.utils.FormFieldFactory;import java.util.*;
public class MedicineLibraryActivity extends BaseActivity{
 private final List<MedicineLibraryItem>items=new ArrayList<>();private Adapter adapter;private EditText search;private boolean editable;
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_medicine_library);editable=getIntent().getBooleanExtra("editable",false);View h=findViewById(R.id.library_header);((TextView)h.findViewById(R.id.header_title)).setText(editable?"管理药品库":"浏览药品库");h.findViewById(R.id.header_back).setOnClickListener(v->finish());h.findViewById(R.id.header_action).setVisibility(View.GONE);search=findViewById(R.id.library_search);search.setOnEditorActionListener((v,a,e)->{refresh();return false;});RecyclerView list=findViewById(R.id.library_list);list.setLayoutManager(new LinearLayoutManager(this));adapter=new Adapter();list.setAdapter(adapter);TextView add=findViewById(R.id.library_add);add.setVisibility(editable?View.VISIBLE:View.GONE);add.setOnClickListener(v->edit(null));refresh();}
 private void refresh(){items.clear();items.addAll(medicineReminders().searchMedicineLibrary(search.getText().toString()));adapter.notifyDataSetChanged();findViewById(R.id.library_empty).setVisibility(items.isEmpty()?View.VISIBLE:View.GONE);}
 private void edit(MedicineLibraryItem old){LinearLayout f=(LinearLayout)getLayoutInflater().inflate(R.layout.view_dialog_form_container,null,false);EditText disease=FormFieldFactory.addTextField(this,f,"疾病分类","高血压",false),name=FormFieldFactory.addTextField(this,f,"药品名称","硝苯地平",false),brand=FormFieldFactory.addTextField(this,f,"品牌名","可选",false),type=FormFieldFactory.addTextField(this,f,"类型","降压药",false),desc=FormFieldFactory.addTextField(this,f,"说明","用药说明",true);if(old!=null){disease.setText(old.disease);name.setText(old.name);brand.setText(old.brand);type.setText(old.type);desc.setText(old.description);}AlertDialog d=new AlertDialog.Builder(this).setTitle(old==null?"新增药品":"编辑药品").setView(f).setPositiveButton(R.string.common_save,null).setNegativeButton(R.string.common_cancel,null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("请输入药品名");return;}MedicineLibraryItem item=new MedicineLibraryItem(old==null?0:old.id,disease.getText().toString().trim(),name.getText().toString().trim(),brand.getText().toString().trim(),type.getText().toString().trim(),desc.getText().toString().trim());if(old==null)medicineReminders().addLibraryItem(item);else medicineReminders().updateLibraryItem(item);refresh();d.dismiss();}));d.show();}
 private class Adapter extends RecyclerView.Adapter<VH>{public VH onCreateViewHolder(android.view.ViewGroup p,int t){return new VH(getLayoutInflater().inflate(R.layout.item_medicine_library,p,false));}public void onBindViewHolder(VH h,int p){MedicineLibraryItem i=items.get(p);h.title.setText(i.name+" · "+i.brand);h.body.setText(i.disease+" / "+i.type+"\n"+i.description);h.itemView.setOnClickListener(v->{if(editable)edit(i);});h.itemView.setOnLongClickListener(v->{if(editable)new AlertDialog.Builder(MedicineLibraryActivity.this).setTitle("删除药品").setMessage(i.name).setPositiveButton(R.string.common_delete,(d,w)->{medicineReminders().deleteLibraryItem(i);refresh();}).setNegativeButton(R.string.common_cancel,null).show();return true;});}public int getItemCount(){return items.size();}}
 private static class VH extends RecyclerView.ViewHolder{TextView title,body;VH(View v){super(v);title=v.findViewById(R.id.library_item_title);body=v.findViewById(R.id.library_item_body);}}
}
